[package]
name = "rust-ipfs-toy"
version = "0.1.0"
authors = ["Micah Elizabeth Scott <micah@scanlime.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipfs-embed = "0.4.0"
libipld = "0.4.0"
multibase = "0.8.0"
sled = "0.34.0"
async-std = "1.6.0"
