[package]
name = "rectangle-device"
version = "0.1.0"
authors = ["Micah Elizabeth Scott <micah@scanlime.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rectangle-device-player = { version = "0.1.0", path = "player" }
env_logger = "0.7.1"
log = "0.4.11"
async-std = { version = "1.6.0", features = ["unstable"] }
futures = "0.3.1"
libipld = "0.4.0"
libp2p = "0.28.1"
libp2p-bitswap = "0.7.0"
mpeg2ts = "0.1.1"
m3u8-rs = "1.0"
rand = "0.7.3"
serde = "1.0.116"
reqwest = { version = "0.10.8", features = ["json"] }
tokio = "0.2.22"
leb128 = "0.2.4"
rust-runc = "0.1.1"
dkregistry = "0.4.0"

[workspace]
members = [ "player" ]
