[package]
name = "rectangle-device-player"
version = "0.1.0"
authors = ["Micah Elizabeth Scott <micah@scanlime.org>"]
edition = "2018"

[dependencies]
askama = "0.10.3"

[build-dependencies]
build-deps = "0.1.4"
